name: Build and deploy ASP.Net Core app to Azure Web App - videoplatformph

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read # Required for actions/checkout

    steps:
      - uses: actions/checkout@v4

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Restore dependencies
        run: dotnet restore ./VideoPlatform.Web/VideoPlatform.Web.csproj

      - name: Build Web project
        run: dotnet build ./VideoPlatform.Web/VideoPlatform.Web.csproj --configuration Release --no-restore

      - name: Publish Web project
        run: dotnet publish ./VideoPlatform.Web/VideoPlatform.Web.csproj -c Release -o ./publish --no-build

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ./publish

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_63DA4E333B0B41BC9FE862DEC16B8BE4 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_33460434502F4071B9270C5D867C69EF }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_1169C1BCC3F14E61BF0B13BDBE554F8E }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'videoplatformph'
          slot-name: 'Production'
          package: .
